import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

export type Language = 'es' | 'en' | 'de';

export const LANGUAGE_LABELS: Record<Language, string> = {
  es: 'Español',
  en: 'English',
  de: 'Deutsch',
};

export const LANGUAGE_FLAGS: Record<Language, string> = {
  es: '🇪🇸',
  en: '🇺🇸',
  de: '🇩🇪',
};

// Translation dictionary type
type TranslationDict = Record<string, string>;

const translations: Record<Language, TranslationDict> = {
  es: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventario',
    'nav.movements': 'Movimientos',
    'nav.locations': 'Ubicaciones',
    'nav.suppliers': 'Proveedores',
    'nav.auditLogs': 'Auditoría',
    'nav.reports': 'Reportes',
    'nav.settings': 'Configuración',
    'nav.team': 'Equipo',

    // Dashboard
    'dashboard.title': 'Tablero de {org}',
    'dashboard.titleDefault': 'Tablero',
    'dashboard.subtitle': 'Tu inventario de un vistazo',
    'dashboard.products': 'Productos',
    'dashboard.value': 'Valor',
    'dashboard.lowStock': 'Stock Bajo',
    'dashboard.categories': 'Categorías',
    'dashboard.team': 'Equipo',

    // Inventory
    'inventory.title': 'Inventario',
    'inventory.subtitle': 'Gestiona tus productos',
    'inventory.searchPlaceholder': 'Buscar productos...',
    'inventory.allCategories': 'Todas las Categorías',
    'inventory.allStatus': 'Todos los Estados',
    'inventory.inStock': 'En Stock',
    'inventory.lowStock': 'Stock Bajo',
    'inventory.outOfStock': 'Sin Stock',
    'inventory.analyzeAI': 'Analizar con IA',
    'inventory.importCSV': 'Importar CSV',
    'inventory.export': 'Exportar',
    'inventory.labels': 'Etiquetas',
    'inventory.noProducts': 'Sin productos aún',
    'inventory.noProductsDesc': 'Agrega tu primer producto para empezar a gestionar tu inventario',
    'inventory.noResults': 'No se encontraron productos',
    'inventory.noResultsDesc': 'Intenta ajustar tu búsqueda o filtros',
    'inventory.noStockLocation': 'Sin productos con stock en esta ubicación',
    'inventory.addFirst': 'Agregar Primer Producto',
    'inventory.deleteTitle': 'Eliminar Producto',
    'inventory.deleteDesc': '¿Estás seguro de que quieres eliminar "{name}"? Esta acción no se puede deshacer.',

    // Movements
    'movements.title': 'Movimientos',
    'movements.subtitle': 'Registra entradas/salidas y transferencias',
    'movements.incoming': 'Entrada',
    'movements.outgoing': 'Salida',
    'movements.recordIncoming': 'Registrar Entrada',
    'movements.recordOutgoing': 'Registrar Salida',
    'movements.product': 'Producto',
    'movements.selectProduct': 'Seleccionar producto',
    'movements.location': 'Ubicación',
    'movements.selectLocation': 'Seleccionar ubicación',
    'movements.quantity': 'Cantidad',
    'movements.enterQuantity': 'Ingresa la cantidad',
    'movements.notes': 'Notas (opcional)',
    'movements.addNotes': 'Agregar notas...',
    'movements.recentIncoming': 'Entradas Recientes',
    'movements.recentOutgoing': 'Salidas Recientes',
    'movements.noMovements': 'Sin movimientos de {type} aún',
    'movements.noMovementsDesc': 'Registra tu primer movimiento de {type} arriba',

    // Locations
    'locations.title': 'Ubicaciones',
    'locations.subtitle': 'Gestiona almacenes y transferencias',
    'locations.locations': 'Ubicaciones',
    'locations.transfers': 'Transferencias',
    'locations.addLocation': 'Agregar Ubicación',
    'locations.editLocation': 'Editar Ubicación',
    'locations.newTransfer': 'Nueva Transferencia',
    'locations.transferHistory': 'Historial de Transferencias',
    'locations.noLocations': 'Sin ubicaciones aún',
    'locations.noLocationsDesc': 'Agrega tu primer almacén o tienda para rastrear inventario por ubicación',
    'locations.noTransfers': 'Sin transferencias aún',
    'locations.noTransfersDesc': 'Crea tu primera transferencia para mover stock entre ubicaciones',
    'locations.deleteTitle': 'Eliminar Ubicación',
    'locations.deleteDesc': '¿Estás seguro de que quieres eliminar "{name}"? Esto también eliminará todos los registros de stock de esta ubicación. Esta acción no se puede deshacer.',
    'locations.name': 'Nombre',
    'locations.type': 'Tipo',
    'locations.address': 'Dirección',
    'locations.status': 'Estado',
    'locations.warehouse': 'Almacén',
    'locations.store': 'Tienda',
    'locations.central': 'Central',
    'locations.active': 'Activo',
    'locations.inactive': 'Inactivo',

    // Suppliers
    'suppliers.title': 'Proveedores',
    'suppliers.subtitle': 'Gestiona tus relaciones con proveedores.',
    'suppliers.addSupplier': 'Agregar Proveedor',
    'suppliers.editSupplier': 'Editar Proveedor',
    'suppliers.supplierList': 'Lista de Proveedores',
    'suppliers.company': 'Empresa',
    'suppliers.contact': 'Contacto',
    'suppliers.email': 'Email',
    'suppliers.phone': 'Teléfono',
    'suppliers.status': 'Estado',
    'suppliers.actions': 'Acciones',
    'suppliers.active': 'Activo',
    'suppliers.inactive': 'Inactivo',
    'suppliers.companyName': 'Nombre de Empresa *',
    'suppliers.contactPerson': 'Persona de Contacto',
    'suppliers.deleteTitle': 'Eliminar Proveedor',
    'suppliers.deleteDesc': '¿Estás seguro de que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
    'suppliers.noSuppliers': 'Sin proveedores aún. ¡Agrega tu primer proveedor para empezar!',
    'suppliers.updateSupplier': 'Actualizar Proveedor',

    // Audit Logs
    'audit.title': 'Registros de Auditoría',
    'audit.subtitle': 'Registra todos los cambios de inventario y acciones de usuarios para cumplimiento',
    'audit.activityLog': 'Registro de Actividad',
    'audit.activityLogDesc': 'Historial completo de todas las modificaciones de datos',
    'audit.timestamp': 'Fecha',
    'audit.table': 'Tabla',
    'audit.record': 'Registro',
    'audit.action': 'Acción',
    'audit.changedFields': 'Campos Modificados',
    'audit.details': 'Detalles',
    'audit.allTables': 'Todas las Tablas',
    'audit.allActions': 'Todas las Acciones',
    'audit.created': 'Creado',
    'audit.updated': 'Actualizado',
    'audit.deleted': 'Eliminado',
    'audit.loading': 'Cargando registros...',
    'audit.noLogs': 'No se encontraron registros. Los cambios aparecerán aquí al modificar datos de inventario.',
    'audit.filterByTable': 'Filtrar por tabla',
    'audit.filterByAction': 'Filtrar por acción',

    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Administra tu cuenta y preferencias de la aplicación.',
    'settings.saving': 'Guardando...',
    'settings.profileSettings': 'Configuración de Perfil',
    'settings.profileDesc': 'Tu información de cuenta.',
    'settings.appearance': 'Apariencia',
    'settings.appearanceDesc': 'Personaliza el aspecto visual.',
    'settings.darkMode': 'Modo Oscuro',
    'settings.darkModeDesc': 'Alterna entre temas claro y oscuro.',
    'settings.notifications': 'Notificaciones',
    'settings.notificationsDesc': 'Configura tus preferencias de notificación.',
    'settings.lowStockAlerts': 'Alertas de Stock Bajo',
    'settings.lowStockAlertsDesc': 'Recibe alertas cuando los artículos estén bajos.',
    'settings.newMovements': 'Nuevos Movimientos',
    'settings.newMovementsDesc': 'Notificar sobre entradas/salidas de stock.',
    'settings.weeklyReport': 'Reporte Semanal',
    'settings.weeklyReportDesc': 'Recibe un resumen semanal del inventario.',
    'settings.fullAccess': 'Acceso Total',
    'settings.role': 'Rol',
    'settings.user': 'Usuario',

    // Team
    'team.title': 'Gestión de Equipo',
    'team.subtitle': 'Administra los miembros de tu organización y sus permisos.',
    'team.inviteMember': 'Invitar Miembro',
    'team.inviteNew': 'Invitar Nuevo Miembro',
    'team.inviteDesc': 'Ingresa el email y selecciona el rol para el nuevo miembro de tu organización.',
    'team.sendInvitation': 'Enviar Invitación',
    'team.licenseUsage': 'Uso de Licencias',
    'team.admins': 'Administradores',
    'team.warehouseManagers': 'Jefes de Almacén',
    'team.staff': 'Personal',
    'team.orgMembers': 'Miembros de la Organización',
    'team.orgMembersDescAdmin': 'Gestiona los roles y permisos de cada miembro.',
    'team.orgMembersDescView': 'Vista de los miembros de tu organización.',
    'team.you': 'Tú',
    'team.apply': 'Aplicar',
    'team.remove': 'Eliminar',
    'team.addCustomRole': 'Agregar cargo personalizado',
    'team.licenseLimitReached': 'Límite de licencias alcanzado. Contacte a ventas.',

    // Reports
    'reports.title': 'Gestor de Reportes',
    'reports.subtitle': 'Crea reportes de inventario personalizados',
    'reports.config': 'Configuración del Reporte',
    'reports.configDesc': 'Selecciona las columnas a incluir en tu reporte',
    'reports.reportTitle': 'Título del Reporte',
    'reports.reportTitlePlaceholder': 'Ingresa el título del reporte',
    'reports.columnsToInclude': 'Columnas a Incluir',
    'reports.additionalNotes': 'Notas Adicionales',
    'reports.notesPlaceholder': 'Agrega notas para incluir al final del reporte PDF...',
    'reports.generatePDF': 'Generar PDF',
    'reports.exportCSV': 'Exportar CSV',
    'reports.importHistory': 'Historial de Importación',
    'reports.importHistoryDesc': 'Importaciones masivas recientes',
    'reports.noImports': 'Sin importaciones aún',
    'reports.preview': 'Vista Previa',
    'reports.previewDesc': '{count} productos serán incluidos • {cols} columnas seleccionadas',
    'reports.andMore': '... y {count} productos más',
    'reports.completed': 'Completado',
    'reports.failed': 'Fallido',
    'reports.pending': 'Pendiente',
    'reports.imported': 'importados',
    'reports.failedRows': 'fallidos',
    'reports.selectAtLeastOne': 'Selecciona al menos una columna',
    'reports.pdfSuccess': 'Reporte generado exitosamente',
    'reports.pdfError': 'Error al generar el reporte',
    'reports.csvSuccess': 'CSV exportado exitosamente',
    'reports.defaultTitle': 'Reporte de Inventario',
    'reports.exportDate': 'Fecha de exportación',
    'reports.page': 'Página',
    'reports.of': 'de',
    'reports.totalProducts': 'Total de Productos',
    'reports.generatedBy': 'Generado por Inventra',
    'reports.notes': 'Notas',

    // Report columns
    'col.name': 'Nombre del Producto',
    'col.name.pdf': 'Nombre',
    'col.sku': 'SKU',
    'col.serial_number': 'Número de Serie',
    'col.serial_number.pdf': 'N° Serie',
    'col.category': 'Categoría',
    'col.quantity': 'Cantidad',
    'col.unit_price': 'Precio Unitario',
    'col.unit_price.pdf': 'Precio Unit.',
    'col.cost_price': 'Precio de Costo',
    'col.cost_price.pdf': 'Costo',
    'col.reorder_point': 'Punto de Reorden',
    'col.reorder_point.pdf': 'Pto. Reorden',
    'col.status_category': 'Estado',
    'col.custodian': 'Custodio',
    'col.micro_location': 'Micro Ubicación',
    'col.micro_location.pdf': 'Micro Ubic.',

    // Common
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.create': 'Crear',
    'common.update': 'Actualizar',
    'common.save': 'Guardar',
    'common.loading': 'Cargando...',
    'common.signOut': 'Cerrar Sesión',
    'common.signedInAs': 'Conectado como',
    'common.menu': 'Menú',
    'common.comingSoon': 'Próximamente',
    'common.active': 'Activo',
    'common.all': 'Todos',
    'common.allLocations': 'Todas las Ubicaciones',
    'common.search': 'Buscar',
    'common.products': 'Productos',
    'common.categories': 'Categorías',
    'common.suppliers': 'Proveedores',
    'common.locations': 'Ubicaciones',
    'common.stockLevels': 'Niveles de Stock',
    'common.internalTransfers': 'Transferencias Internas',

    // Suite Menu
    'suite.title': 'Ecosistema Ciméntica Solutions',
    'suite.subtitle': 'Soluciones empresariales integradas',
    'suite.inventra': 'Gestión de Inventario',
    'suite.finance': 'Gestión Financiera',
    'suite.hr': 'Recursos Humanos',
    'suite.fleet': 'Gestión de Flota',

    // Header menu items
    'header.suppliers': 'Proveedores',
    'header.auditLogs': 'Auditoría',
    'header.team': 'Equipo',
    'header.settings': 'Configuración',

    // Roles
    'role.super_admin': 'Super Admin',
    'role.admin': 'Administrador',
    'role.warehouse_manager': 'Jefe de Almacén',
    'role.staff': 'Personal',
    'role.noRole': 'Sin rol',

    // AI
    'ai.assistant': 'Inventra AI Assistant',
    'ai.generateIA': 'Generar IA',

    // Language
    'language.label': 'Idioma',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventory',
    'nav.movements': 'Movements',
    'nav.locations': 'Locations',
    'nav.suppliers': 'Suppliers',
    'nav.auditLogs': 'Audit Logs',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.team': 'Team',

    // Dashboard
    'dashboard.title': '{org} Dashboard',
    'dashboard.titleDefault': 'Dashboard',
    'dashboard.subtitle': 'Your inventory at a glance',
    'dashboard.products': 'Products',
    'dashboard.value': 'Value',
    'dashboard.lowStock': 'Low Stock',
    'dashboard.categories': 'Categories',
    'dashboard.team': 'Team',

    // Inventory
    'inventory.title': 'Inventory',
    'inventory.subtitle': 'Manage your products',
    'inventory.searchPlaceholder': 'Search products...',
    'inventory.allCategories': 'All Categories',
    'inventory.allStatus': 'All Status',
    'inventory.inStock': 'In Stock',
    'inventory.lowStock': 'Low Stock',
    'inventory.outOfStock': 'Out of Stock',
    'inventory.analyzeAI': 'Analyze with AI',
    'inventory.importCSV': 'Import CSV',
    'inventory.export': 'Export',
    'inventory.labels': 'Labels',
    'inventory.noProducts': 'No products yet',
    'inventory.noProductsDesc': 'Add your first product to start managing your inventory',
    'inventory.noResults': 'No products found',
    'inventory.noResultsDesc': 'Try adjusting your search or filters',
    'inventory.noStockLocation': 'No products with stock at this location',
    'inventory.addFirst': 'Add First Product',
    'inventory.deleteTitle': 'Delete Product',
    'inventory.deleteDesc': 'Are you sure you want to delete "{name}"? This action cannot be undone.',

    // Movements
    'movements.title': 'Movements',
    'movements.subtitle': 'Track stock in/out and transfers',
    'movements.incoming': 'Incoming',
    'movements.outgoing': 'Outgoing',
    'movements.recordIncoming': 'Record Incoming',
    'movements.recordOutgoing': 'Record Outgoing',
    'movements.product': 'Product',
    'movements.selectProduct': 'Select product',
    'movements.location': 'Location',
    'movements.selectLocation': 'Select location',
    'movements.quantity': 'Quantity',
    'movements.enterQuantity': 'Enter quantity',
    'movements.notes': 'Notes (optional)',
    'movements.addNotes': 'Add notes...',
    'movements.recentIncoming': 'Recent Incoming',
    'movements.recentOutgoing': 'Recent Outgoing',
    'movements.noMovements': 'No {type} movements yet',
    'movements.noMovementsDesc': 'Record your first {type} movement above',

    // Locations
    'locations.title': 'Locations',
    'locations.subtitle': 'Manage warehouses & transfers',
    'locations.locations': 'Locations',
    'locations.transfers': 'Transfers',
    'locations.addLocation': 'Add Location',
    'locations.editLocation': 'Edit Location',
    'locations.newTransfer': 'New Transfer',
    'locations.transferHistory': 'Transfer History',
    'locations.noLocations': 'No locations yet',
    'locations.noLocationsDesc': 'Add your first warehouse or store to start tracking inventory by location',
    'locations.noTransfers': 'No transfers yet',
    'locations.noTransfersDesc': 'Create your first transfer to move stock between locations',
    'locations.deleteTitle': 'Delete Location',
    'locations.deleteDesc': 'Are you sure you want to delete "{name}"? This will also remove all stock records for this location. This action cannot be undone.',
    'locations.name': 'Name',
    'locations.type': 'Type',
    'locations.address': 'Address',
    'locations.status': 'Status',
    'locations.warehouse': 'Warehouse',
    'locations.store': 'Store',
    'locations.central': 'Central',
    'locations.active': 'Active',
    'locations.inactive': 'Inactive',

    // Suppliers
    'suppliers.title': 'Suppliers',
    'suppliers.subtitle': 'Manage your supplier relationships.',
    'suppliers.addSupplier': 'Add Supplier',
    'suppliers.editSupplier': 'Edit Supplier',
    'suppliers.supplierList': 'Supplier List',
    'suppliers.company': 'Company',
    'suppliers.contact': 'Contact',
    'suppliers.email': 'Email',
    'suppliers.phone': 'Phone',
    'suppliers.status': 'Status',
    'suppliers.actions': 'Actions',
    'suppliers.active': 'Active',
    'suppliers.inactive': 'Inactive',
    'suppliers.companyName': 'Company Name *',
    'suppliers.contactPerson': 'Contact Person',
    'suppliers.deleteTitle': 'Delete Supplier',
    'suppliers.deleteDesc': 'Are you sure you want to delete "{name}"? This action cannot be undone.',
    'suppliers.noSuppliers': 'No suppliers yet. Add your first supplier to get started!',
    'suppliers.updateSupplier': 'Update Supplier',

    // Audit Logs
    'audit.title': 'Audit Logs',
    'audit.subtitle': 'Track all inventory changes and user actions for compliance',
    'audit.activityLog': 'Activity Log',
    'audit.activityLogDesc': 'Complete history of all data modifications',
    'audit.timestamp': 'Timestamp',
    'audit.table': 'Table',
    'audit.record': 'Record',
    'audit.action': 'Action',
    'audit.changedFields': 'Changed Fields',
    'audit.details': 'Details',
    'audit.allTables': 'All Tables',
    'audit.allActions': 'All Actions',
    'audit.created': 'Created',
    'audit.updated': 'Updated',
    'audit.deleted': 'Deleted',
    'audit.loading': 'Loading audit logs...',
    'audit.noLogs': 'No audit logs found. Changes will appear here as you modify inventory data.',
    'audit.filterByTable': 'Filter by table',
    'audit.filterByAction': 'Filter by action',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and application preferences.',
    'settings.saving': 'Saving...',
    'settings.profileSettings': 'Profile Settings',
    'settings.profileDesc': 'Your account information.',
    'settings.appearance': 'Appearance',
    'settings.appearanceDesc': 'Customize the visual look.',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDesc': 'Toggle between light and dark themes.',
    'settings.notifications': 'Notifications',
    'settings.notificationsDesc': 'Configure your notification preferences.',
    'settings.lowStockAlerts': 'Low Stock Alerts',
    'settings.lowStockAlertsDesc': 'Get alerts when items run low.',
    'settings.newMovements': 'New Movements',
    'settings.newMovementsDesc': 'Notify on stock incoming/outgoing.',
    'settings.weeklyReport': 'Weekly Report',
    'settings.weeklyReportDesc': 'Receive a weekly inventory summary.',
    'settings.fullAccess': 'Full Access',
    'settings.role': 'Role',
    'settings.user': 'User',

    // Team
    'team.title': 'Team Management',
    'team.subtitle': 'Manage your organization members and their permissions.',
    'team.inviteMember': 'Invite Member',
    'team.inviteNew': 'Invite New Member',
    'team.inviteDesc': 'Enter the email and select the role for the new organization member.',
    'team.sendInvitation': 'Send Invitation',
    'team.licenseUsage': 'License Usage',
    'team.admins': 'Admins',
    'team.warehouseManagers': 'Warehouse Managers',
    'team.staff': 'Staff',
    'team.orgMembers': 'Organization Members',
    'team.orgMembersDescAdmin': 'Manage the roles and permissions of each member.',
    'team.orgMembersDescView': 'View of your organization members.',
    'team.you': 'You',
    'team.apply': 'Apply',
    'team.remove': 'Remove',
    'team.addCustomRole': 'Add custom role',
    'team.licenseLimitReached': 'License limit reached. Contact sales.',

    // Reports
    'reports.title': 'Report Manager',
    'reports.subtitle': 'Create customized inventory reports',
    'reports.config': 'Report Configuration',
    'reports.configDesc': 'Select the columns to include in your report',
    'reports.reportTitle': 'Report Title',
    'reports.reportTitlePlaceholder': 'Enter report title',
    'reports.columnsToInclude': 'Columns to Include',
    'reports.additionalNotes': 'Additional Notes',
    'reports.notesPlaceholder': 'Add notes to include at the end of the PDF report...',
    'reports.generatePDF': 'Generate PDF',
    'reports.exportCSV': 'Export CSV',
    'reports.importHistory': 'Import History',
    'reports.importHistoryDesc': 'Recent bulk imports',
    'reports.noImports': 'No imports yet',
    'reports.preview': 'Preview',
    'reports.previewDesc': '{count} products will be included • {cols} columns selected',
    'reports.andMore': '... and {count} more products',
    'reports.completed': 'Completed',
    'reports.failed': 'Failed',
    'reports.pending': 'Pending',
    'reports.imported': 'imported',
    'reports.failedRows': 'failed',
    'reports.selectAtLeastOne': 'Select at least one column',
    'reports.pdfSuccess': 'Report generated successfully',
    'reports.pdfError': 'Error generating report',
    'reports.csvSuccess': 'CSV exported successfully',
    'reports.defaultTitle': 'Inventory Report',
    'reports.exportDate': 'Export date',
    'reports.page': 'Page',
    'reports.of': 'of',
    'reports.totalProducts': 'Total Products',
    'reports.generatedBy': 'Generated by Inventra',
    'reports.notes': 'Notes',

    // Report columns
    'col.name': 'Product Name',
    'col.name.pdf': 'Name',
    'col.sku': 'SKU',
    'col.serial_number': 'Serial Number',
    'col.serial_number.pdf': 'Serial No.',
    'col.category': 'Category',
    'col.quantity': 'Quantity',
    'col.unit_price': 'Unit Price',
    'col.unit_price.pdf': 'Unit Price',
    'col.cost_price': 'Cost Price',
    'col.cost_price.pdf': 'Cost',
    'col.reorder_point': 'Reorder Point',
    'col.reorder_point.pdf': 'Reorder Pt.',
    'col.status_category': 'Status',
    'col.custodian': 'Custodian',
    'col.micro_location': 'Micro Location',
    'col.micro_location.pdf': 'Micro Loc.',

    // Common
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.save': 'Save',
    'common.loading': 'Loading...',
    'common.signOut': 'Sign Out',
    'common.signedInAs': 'Signed in as',
    'common.menu': 'Menu',
    'common.comingSoon': 'Coming Soon',
    'common.active': 'Active',
    'common.all': 'All',
    'common.allLocations': 'All Locations',
    'common.search': 'Search',
    'common.products': 'Products',
    'common.categories': 'Categories',
    'common.suppliers': 'Suppliers',
    'common.locations': 'Locations',
    'common.stockLevels': 'Stock Levels',
    'common.internalTransfers': 'Internal Transfers',

    // Suite Menu
    'suite.title': 'Ciméntica Solutions Ecosystem',
    'suite.subtitle': 'Integrated business solutions',
    'suite.inventra': 'Inventory Management',
    'suite.finance': 'Financial Management',
    'suite.hr': 'Human Resources',
    'suite.fleet': 'Fleet Management',

    // Header menu items
    'header.suppliers': 'Suppliers',
    'header.auditLogs': 'Audit Logs',
    'header.team': 'Team',
    'header.settings': 'Settings',

    // Roles
    'role.super_admin': 'Super Admin',
    'role.admin': 'Admin',
    'role.warehouse_manager': 'Warehouse Manager',
    'role.staff': 'Staff',
    'role.noRole': 'No role',

    // AI
    'ai.assistant': 'Inventra AI Assistant',
    'ai.generateIA': 'Generate AI',

    // Language
    'language.label': 'Language',
  },
  de: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventar',
    'nav.movements': 'Bewegungen',
    'nav.locations': 'Standorte',
    'nav.suppliers': 'Lieferanten',
    'nav.auditLogs': 'Protokolle',
    'nav.reports': 'Berichte',
    'nav.settings': 'Einstellungen',
    'nav.team': 'Team',

    // Dashboard
    'dashboard.title': '{org} Dashboard',
    'dashboard.titleDefault': 'Dashboard',
    'dashboard.subtitle': 'Ihr Inventar auf einen Blick',
    'dashboard.products': 'Produkte',
    'dashboard.value': 'Wert',
    'dashboard.lowStock': 'Niedriger Bestand',
    'dashboard.categories': 'Kategorien',
    'dashboard.team': 'Team',

    // Inventory
    'inventory.title': 'Inventar',
    'inventory.subtitle': 'Produkte verwalten',
    'inventory.searchPlaceholder': 'Produkte suchen...',
    'inventory.allCategories': 'Alle Kategorien',
    'inventory.allStatus': 'Alle Status',
    'inventory.inStock': 'Auf Lager',
    'inventory.lowStock': 'Niedriger Bestand',
    'inventory.outOfStock': 'Nicht vorrätig',
    'inventory.analyzeAI': 'KI-Analyse',
    'inventory.importCSV': 'CSV importieren',
    'inventory.export': 'Exportieren',
    'inventory.labels': 'Etiketten',
    'inventory.noProducts': 'Noch keine Produkte',
    'inventory.noProductsDesc': 'Füge dein erstes Produkt hinzu, um mit der Inventarverwaltung zu beginnen',
    'inventory.noResults': 'Keine Produkte gefunden',
    'inventory.noResultsDesc': 'Versuche, deine Suche oder Filter anzupassen',
    'inventory.noStockLocation': 'Keine Produkte mit Bestand an diesem Standort',
    'inventory.addFirst': 'Erstes Produkt hinzufügen',
    'inventory.deleteTitle': 'Produkt löschen',
    'inventory.deleteDesc': 'Möchtest du „{name}" wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',

    // Movements
    'movements.title': 'Bewegungen',
    'movements.subtitle': 'Warenein-/-ausgang und Transfers verfolgen',
    'movements.incoming': 'Eingang',
    'movements.outgoing': 'Ausgang',
    'movements.recordIncoming': 'Eingang erfassen',
    'movements.recordOutgoing': 'Ausgang erfassen',
    'movements.product': 'Produkt',
    'movements.selectProduct': 'Produkt auswählen',
    'movements.location': 'Standort',
    'movements.selectLocation': 'Standort auswählen',
    'movements.quantity': 'Menge',
    'movements.enterQuantity': 'Menge eingeben',
    'movements.notes': 'Notizen (optional)',
    'movements.addNotes': 'Notizen hinzufügen...',
    'movements.recentIncoming': 'Letzte Eingänge',
    'movements.recentOutgoing': 'Letzte Ausgänge',
    'movements.noMovements': 'Noch keine {type}-Bewegungen',
    'movements.noMovementsDesc': 'Erfasse deine erste {type}-Bewegung oben',

    // Locations
    'locations.title': 'Standorte',
    'locations.subtitle': 'Lager und Transfers verwalten',
    'locations.locations': 'Standorte',
    'locations.transfers': 'Transfers',
    'locations.addLocation': 'Standort hinzufügen',
    'locations.editLocation': 'Standort bearbeiten',
    'locations.newTransfer': 'Neuer Transfer',
    'locations.transferHistory': 'Transfer-Verlauf',
    'locations.noLocations': 'Noch keine Standorte',
    'locations.noLocationsDesc': 'Füge dein erstes Lager oder Geschäft hinzu, um Inventar nach Standort zu verfolgen',
    'locations.noTransfers': 'Noch keine Transfers',
    'locations.noTransfersDesc': 'Erstelle deinen ersten Transfer, um Bestand zwischen Standorten zu verschieben',
    'locations.deleteTitle': 'Standort löschen',
    'locations.deleteDesc': 'Möchtest du „{name}" wirklich löschen? Alle Bestandsdaten für diesen Standort werden ebenfalls gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
    'locations.name': 'Name',
    'locations.type': 'Typ',
    'locations.address': 'Adresse',
    'locations.status': 'Status',
    'locations.warehouse': 'Lager',
    'locations.store': 'Geschäft',
    'locations.central': 'Zentral',
    'locations.active': 'Aktiv',
    'locations.inactive': 'Inaktiv',

    // Suppliers
    'suppliers.title': 'Lieferanten',
    'suppliers.subtitle': 'Verwalte deine Lieferantenbeziehungen.',
    'suppliers.addSupplier': 'Lieferant hinzufügen',
    'suppliers.editSupplier': 'Lieferant bearbeiten',
    'suppliers.supplierList': 'Lieferantenliste',
    'suppliers.company': 'Unternehmen',
    'suppliers.contact': 'Kontakt',
    'suppliers.email': 'E-Mail',
    'suppliers.phone': 'Telefon',
    'suppliers.status': 'Status',
    'suppliers.actions': 'Aktionen',
    'suppliers.active': 'Aktiv',
    'suppliers.inactive': 'Inaktiv',
    'suppliers.companyName': 'Firmenname *',
    'suppliers.contactPerson': 'Ansprechpartner',
    'suppliers.deleteTitle': 'Lieferant löschen',
    'suppliers.deleteDesc': 'Möchtest du „{name}" wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'suppliers.noSuppliers': 'Noch keine Lieferanten. Füge deinen ersten Lieferanten hinzu!',
    'suppliers.updateSupplier': 'Lieferant aktualisieren',

    // Audit Logs
    'audit.title': 'Prüfprotokolle',
    'audit.subtitle': 'Alle Inventaränderungen und Benutzeraktionen für die Compliance verfolgen',
    'audit.activityLog': 'Aktivitätsprotokoll',
    'audit.activityLogDesc': 'Vollständiger Verlauf aller Datenänderungen',
    'audit.timestamp': 'Zeitstempel',
    'audit.table': 'Tabelle',
    'audit.record': 'Datensatz',
    'audit.action': 'Aktion',
    'audit.changedFields': 'Geänderte Felder',
    'audit.details': 'Details',
    'audit.allTables': 'Alle Tabellen',
    'audit.allActions': 'Alle Aktionen',
    'audit.created': 'Erstellt',
    'audit.updated': 'Aktualisiert',
    'audit.deleted': 'Gelöscht',
    'audit.loading': 'Protokolle werden geladen...',
    'audit.noLogs': 'Keine Protokolle gefunden. Änderungen erscheinen hier, wenn Inventardaten geändert werden.',
    'audit.filterByTable': 'Nach Tabelle filtern',
    'audit.filterByAction': 'Nach Aktion filtern',

    // Settings
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Verwalte dein Konto und deine App-Einstellungen.',
    'settings.saving': 'Speichern...',
    'settings.profileSettings': 'Profileinstellungen',
    'settings.profileDesc': 'Deine Kontoinformationen.',
    'settings.appearance': 'Erscheinungsbild',
    'settings.appearanceDesc': 'Passe das visuelle Erscheinungsbild an.',
    'settings.darkMode': 'Dunkelmodus',
    'settings.darkModeDesc': 'Zwischen hellem und dunklem Design wechseln.',
    'settings.notifications': 'Benachrichtigungen',
    'settings.notificationsDesc': 'Konfiguriere deine Benachrichtigungseinstellungen.',
    'settings.lowStockAlerts': 'Niedrigbestand-Warnungen',
    'settings.lowStockAlertsDesc': 'Warnungen bei niedrigem Bestand erhalten.',
    'settings.newMovements': 'Neue Bewegungen',
    'settings.newMovementsDesc': 'Benachrichtigung bei Warenein-/-ausgang.',
    'settings.weeklyReport': 'Wochenbericht',
    'settings.weeklyReportDesc': 'Wöchentliche Inventarzusammenfassung erhalten.',
    'settings.fullAccess': 'Vollzugriff',
    'settings.role': 'Rolle',
    'settings.user': 'Benutzer',

    // Team
    'team.title': 'Teamverwaltung',
    'team.subtitle': 'Verwalte die Mitglieder deiner Organisation und ihre Berechtigungen.',
    'team.inviteMember': 'Mitglied einladen',
    'team.inviteNew': 'Neues Mitglied einladen',
    'team.inviteDesc': 'Gib die E-Mail-Adresse ein und wähle die Rolle für das neue Organisationsmitglied.',
    'team.sendInvitation': 'Einladung senden',
    'team.licenseUsage': 'Lizenznutzung',
    'team.admins': 'Administratoren',
    'team.warehouseManagers': 'Lagerverwalter',
    'team.staff': 'Personal',
    'team.orgMembers': 'Organisationsmitglieder',
    'team.orgMembersDescAdmin': 'Verwalte die Rollen und Berechtigungen jedes Mitglieds.',
    'team.orgMembersDescView': 'Übersicht der Organisationsmitglieder.',
    'team.you': 'Du',
    'team.apply': 'Anwenden',
    'team.remove': 'Entfernen',
    'team.addCustomRole': 'Benutzerdefinierte Rolle hinzufügen',
    'team.licenseLimitReached': 'Lizenzlimit erreicht. Kontaktiere den Vertrieb.',

    // Reports
    'reports.title': 'Berichtsmanager',
    'reports.subtitle': 'Erstelle individuelle Inventarberichte',
    'reports.config': 'Berichtskonfiguration',
    'reports.configDesc': 'Wähle die Spalten für deinen Bericht aus',
    'reports.reportTitle': 'Berichtstitel',
    'reports.reportTitlePlaceholder': 'Berichtstitel eingeben',
    'reports.columnsToInclude': 'Einzubeziehende Spalten',
    'reports.additionalNotes': 'Zusätzliche Notizen',
    'reports.notesPlaceholder': 'Notizen für das Ende des PDF-Berichts hinzufügen...',
    'reports.generatePDF': 'PDF erstellen',
    'reports.exportCSV': 'CSV exportieren',
    'reports.importHistory': 'Importverlauf',
    'reports.importHistoryDesc': 'Kürzliche Massenimporte',
    'reports.noImports': 'Noch keine Importe',
    'reports.preview': 'Vorschau',
    'reports.previewDesc': '{count} Produkte werden einbezogen • {cols} Spalten ausgewählt',
    'reports.andMore': '... und {count} weitere Produkte',
    'reports.completed': 'Abgeschlossen',
    'reports.failed': 'Fehlgeschlagen',
    'reports.pending': 'Ausstehend',
    'reports.imported': 'importiert',
    'reports.failedRows': 'fehlgeschlagen',
    'reports.selectAtLeastOne': 'Wähle mindestens eine Spalte',
    'reports.pdfSuccess': 'Bericht erfolgreich erstellt',
    'reports.pdfError': 'Fehler beim Erstellen des Berichts',
    'reports.csvSuccess': 'CSV erfolgreich exportiert',
    'reports.defaultTitle': 'Inventarbericht',
    'reports.exportDate': 'Exportdatum',
    'reports.page': 'Seite',
    'reports.of': 'von',
    'reports.totalProducts': 'Produkte gesamt',
    'reports.generatedBy': 'Erstellt mit Inventra',
    'reports.notes': 'Notizen',

    // Report columns
    'col.name': 'Produktname',
    'col.name.pdf': 'Name',
    'col.sku': 'SKU',
    'col.serial_number': 'Seriennummer',
    'col.serial_number.pdf': 'Seriennr.',
    'col.category': 'Kategorie',
    'col.quantity': 'Menge',
    'col.unit_price': 'Stückpreis',
    'col.unit_price.pdf': 'Stückpr.',
    'col.cost_price': 'Einkaufspreis',
    'col.cost_price.pdf': 'Kosten',
    'col.reorder_point': 'Nachbestellpunkt',
    'col.reorder_point.pdf': 'Nachbest.',
    'col.status_category': 'Status',
    'col.custodian': 'Verantwortlicher',
    'col.micro_location': 'Mikro-Standort',
    'col.micro_location.pdf': 'Mikro-Std.',

    // Common
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.create': 'Erstellen',
    'common.update': 'Aktualisieren',
    'common.save': 'Speichern',
    'common.loading': 'Laden...',
    'common.signOut': 'Abmelden',
    'common.signedInAs': 'Angemeldet als',
    'common.menu': 'Menü',
    'common.comingSoon': 'Demnächst',
    'common.active': 'Aktiv',
    'common.all': 'Alle',
    'common.allLocations': 'Alle Standorte',
    'common.search': 'Suchen',
    'common.products': 'Produkte',
    'common.categories': 'Kategorien',
    'common.suppliers': 'Lieferanten',
    'common.locations': 'Standorte',
    'common.stockLevels': 'Bestandsniveaus',
    'common.internalTransfers': 'Interne Transfers',

    // Suite Menu
    'suite.title': 'Ciméntica Solutions Ökosystem',
    'suite.subtitle': 'Integrierte Geschäftslösungen',
    'suite.inventra': 'Inventarverwaltung',
    'suite.finance': 'Finanzverwaltung',
    'suite.hr': 'Personalwesen',
    'suite.fleet': 'Flottenverwaltung',

    // Header menu items
    'header.suppliers': 'Lieferanten',
    'header.auditLogs': 'Protokolle',
    'header.team': 'Team',
    'header.settings': 'Einstellungen',

    // Roles
    'role.super_admin': 'Super Admin',
    'role.admin': 'Administrator',
    'role.warehouse_manager': 'Lagerverwalter',
    'role.staff': 'Personal',
    'role.noRole': 'Keine Rolle',

    // AI
    'ai.assistant': 'Inventra KI-Assistent',
    'ai.generateIA': 'KI generieren',

    // Language
    'language.label': 'Sprache',
  },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

const STORAGE_KEY = 'inventra-language';

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    return (saved as Language) || 'es';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  }, []);

  const t = useCallback((key: string, params?: Record<string, string | number>) => {
    let value = translations[language][key] || translations['es'][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        value = value.replace(`{${k}}`, String(v));
      });
    }
    return value;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}

// Helper for AI context - returns language name for prompts
export function getLanguageName(lang: Language): string {
  const names: Record<Language, string> = { es: 'Spanish', en: 'English', de: 'German' };
  return names[lang];
}